services:
  - type: web
    name: epl-match-predictor-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    region: oregon
    envVars:
      - key: CORS_ORIGINS
        value: "*"
      - key: DATABASE_URL
        value: sqlite:///./epl_predictor.db
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
